### ISSUE TITLE
fetch gene name data when node is selected?

### ISSUE THREAD

**Issue by sbridel** [jianhong/GeneNetworkBuilder#1]
Hello,

i wonder how can I return/get the data from a selected node that is highlited in yellow outside the browseNetwork.

In other word, extract the value and do further stuff, like plot the subnetwork of this gene

Could you help please?

**Comment by jianhong** [comment]
Thank you for trying GeneNetworkBuilder. Did you tried `exportNetwork` or `saveXML`  described in [Example using gene expression profile](https://www.bioconductor.org/packages/release/bioc/vignettes/GeneNetworkBuilder/inst/doc/GeneNetworkBuilder_vignettes.html#example-using-gene-expression-profile)
